[package]
name = "rsspec"
version.workspace = true
edition.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true
description = "A Ginkgo/RSpec-inspired BDD testing framework for Rust."

[features]
default = ["macros"]
macros = ["dep:rsspec_macros"]

[dependencies]
rsspec_macros = { path = "../rsspec_macros", version = "0.1.0", optional = true }

[dev-dependencies]
rsspec_macros = { path = "../rsspec_macros", version = "0.1.0" }
